micronaut.application.name=healthcare

micronaut.server.cors.enabled=true

# H2 Database
datasources.default.url=jdbc:h2:file:./data/healthcare;MODE=PostgreSQL;DB_CLOSE_ON_EXIT=FALSE
datasources.default.driverClassName=org.h2.Driver
datasources.default.username=healthcare_user
datasources.default.password=password
datasources.default.dialect=H2